---
- name: Listen for events with webhook plugin
  hosts: all
  
  # Utilize the webhook plugin
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000

  rules:
    - name: Show the games
      condition: event.payload.message == 'list games' and event.payload.etags is selectattr('value', 'match', 'LINUX')
      action:
        run_job_template:
          name: List Games
          organization: Default
          job_args:
            extra_vars:
              ansible_limit: event.payload.problem_host
